export const styles = {
  mainLayout: { width: '100%', height: '100vh', display: 'flex', flexDirection: 'column', backgroundColor: '#0f1114', overflow: 'hidden' },
  headerContainer: { padding: '15px 25px', background: '#111418', borderBottom: '2px solid #fbbf24', flexShrink: 0 },
  flexSpace: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '15px' },
  tituloDorado: { color: '#fbbf24', margin: 0, fontSize: '1.2rem', fontWeight: '800' },
  headerActions: { display: 'flex', gap: '12px', alignItems: 'center' },
  btnProductividad: { background: '#1a1d21', color: '#fff', border: '1px solid #fbbf24', padding: '8px 15px', borderRadius: '5px', fontWeight: 'bold', cursor: 'pointer', fontSize: '0.7rem' },
  contadorBadge: { background: '#1a1d21', padding: '5px 15px', borderRadius: '8px', border: '1px solid #333' },
  labelContador: { color: '#94a3b8', fontSize: '0.7rem' },
  valContador: { color: '#fbbf24', fontWeight: '900', fontSize: '1.1rem', marginLeft: '8px' },
  barraMedios: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', background: '#1a1d21', padding: '8px 15px', borderRadius: '8px', marginTop: '10px', border: '1px dashed #444' },
  btnMediosImport: { color: '#fff', border: 'none', padding: '6px 12px', borderRadius: '4px', fontWeight: 'bold', fontSize: '0.7rem' },
  btnMediosExport: { color: '#fff', border: 'none', padding: '6px 12px', borderRadius: '4px', fontWeight: 'bold', fontSize: '0.7rem' },
  subLabel: { fontSize: '0.6rem', color: '#64748b', fontWeight: 'bold' },
  tableContainer: { flex: 1, padding: '10px 25px 25px 25px', overflow: 'hidden', display: 'flex', flexDirection: 'column' },
  scrollWrapper: { flex: 1, overflowY: 'scroll', overflowX: 'scroll', border: '1px solid #222', borderRadius: '6px', background: '#111418' },
  tableStyle: { width: '100%', minWidth: '1700px', borderCollapse: 'collapse' }, 
  theadStyle: { position: 'sticky', top: 0, background: '#16191e', zIndex: 10 }, 
  thStyle: { padding: '12px', textAlign: 'left', color: '#fbbf24', borderBottom: '2px solid #222', fontSize: '0.7rem' },
  tdStyle: { padding: '12px', borderBottom: '1px solid #1f242d', color: '#e2e8f0', fontSize: '0.85rem' },
  trStyle: { borderBottom: '1px solid #111', background: '#111418', transition: "all 0.15s ease" },
  waitingState: { textAlign: 'center', padding: '100px', color: '#64748b' },
  badge: { padding: '4px 10px', borderRadius: '5px', fontSize: '0.65rem', color: '#fff', fontWeight: 'bold' },
  fechaBadge: { color: '#fbbf24', fontFamily: 'monospace', fontWeight: 'bold', fontSize: '0.85rem' },
  btnVisor: { background: '#fbbf24', color: '#000', border: 'none', padding: '6px 12px', borderRadius: '4px', fontWeight: 'bold', cursor: 'pointer', fontSize: '0.7rem' },
  btnEditar: { background: '#1e293b', border: '1px solid #475569', borderRadius: '4px', padding: '5px 8px', cursor: 'pointer', fontSize: '0.85rem' },
  containerFlujo: { display: 'flex', gap: '8px', alignItems: 'center', background: 'rgba(0,0,0,0.3)', padding: '4px 8px', borderRadius: '6px', border: '1px solid #1e293b', width: 'fit-content' },
  iconFlujoBase: { padding: '5px', borderRadius: '4px', fontSize: '0.95rem', transition: 'all 0.2s ease', display: 'inline-flex', justifyContent: 'center', alignItems: 'center', background: "none", border: "none" },
  btnReabrir: { background: '#0284c7', color: '#fff', border: '1px solid #0369a1', borderRadius: '4px', padding: '5px 8px', cursor: 'pointer', fontSize: '0.85rem', display: 'inline-flex', justifyContent: 'center', alignItems: 'center' }
};